Hotfix – assets and tags
inleadmedia/rest-api pull request #25
Opened 2019-11-06 12:47 UTC by guddo

2019-11-06 12:48 UTC, guddo commented
Here you go @rimi-itk

2019-11-06 12:59 UTC, AnatolyMuntean commented
Please note that migrations package has been removed to at least bring the sources to life, so composer related commands are executed.
The migrations package - https://packagist.org/packages/antimattr/mongodb-migrations-bundle - was removed from the repo itself - https://github.com/antimattr/mongodb-migrations-bundle.

2019-11-06 13:05 UTC, rimi-itk requested changes
A few comments have been added. Please address and then we're ready for go!

2019-11-06 13:05 UTC, rimi-itk commented on app/config/config.yml
> +#    namespace: "Bpi\ApiBundle\Migrations\MongoDB"
Unused code should be deleted, not just commented out.

2019-11-06 13:05 UTC, rimi-itk commented on src/Bpi/ApiBundle/Resources/config/doctrine/Aggregate.Agency.mongodb.yml
> +
Superfluous blank line.

2019-11-06 13:05 UTC, rimi-itk commented on src/Bpi/ApiBundle/Resources/config/doctrine/ValueObject.Assets.Name.mongodb.yml
> +    Name:
This should be `name` (all lowercase), right? The fields names in other `*.mongodb.yml` files are all lowercase.

2019-11-15 12:59 UTC, rimi-itk approved these changes
Looks really good. Thanks.

2019-11-18 10:04 UTC, rimi-itk approved these changes

2021-03-17 13:58 UTC, merged